[frontmatter]
id = 50806108
title = "Polluted Marrow"
authors = ["PandaHero"]
summary = "Max has been looping through this wretched week over and over in search of a less fatal outcome, but after yet another particularly bad ending, she's driven to do a little more than just reset. Consequences be damned."

[frontmatter.tags]
rating = "Not Rated"
warnings = ["Creator Chose Not To Use Archive Warnings"]
categories = ["F/F"]
fandoms = ["Life is Strange (Video Game)"]
relationships = [
    "Rachel Amber/Maxine \"Max\" Caulfield/Chloe Price",
    "Rachel Amber/Chloe Price",
]
characters = [
    "Maxine \"Max\" Caulfield",
    "Chloe Price (Life is Strange)",
    "Rachel Amber",
    "Joyce Price",
    "David Madsen",
    "Mark Jefferson",
    "Victoria Chase (Life is Strange)",
    "Kate Marsh",
    "Warren Graham",
    "Vanessa Caulfield",
]
additional = [
    "Post-Traumatic Stress Disorder - PTSD",
    "Blood and Injury",
    "Nosebleed",
    "Nightmares",
    "Implied/Referenced Rape/Non-con",
    "Implied/Referenced Suicide",
    "Time Travel",
    "Rachel Amber Lives",
    "Panic Attacks",
    "Underage Drinking",
    "Mark Jefferson Is His Own Warning",
    "aka max gets her happy timeline but is way too fucked up to properly enjoy it ,:)",
    "no beta we die like rachel amber (except she's not dead in this one i promise ",
    "this is solidly an everybody lives au. just with a big side of Trauma",
    "will be adding more tags as I go",
    "Dissociation",
    "Mild Gore",
    "Non-Consensual Drug Use",
    "Implied/Referenced Self-Harm",
]

[frontmatter.associations]
language = "English"
series = []
collections = []

[frontmatter.stats]
published = 2023-10-13
updated = 2025-02-18
words = 80_296
chapters = "9/?"
comments = 262
kudos = 898
bookmarks = 204
hits = 19_722

[story]
summary = "Max has been looping through this wretched week over and over in search of a less fatal outcome, but after yet another particularly bad ending, she's driven to do a little more than just reset. Consequences be damned."
start_notes = """oh boy, this got out of hand. welcome to my very self-indulgent rachel-is-alive au, resurrected from a wip so old bts hadn't even come out yet when i started it.
so i totally did not just end up in a coincidentally timed lis rabbit hole that left me so desperate for amberpricefield that i decided to start a dumb little multichap. totally. updates will probably be slow and sporadic, and i have no idea if i'm going to be cranking out chapters as long as this on the regular. i just really wanted a glimpse of everyone's thought process in this one, but i had a lot of fun doing all three povs so i might keep it up. who knows.
title is taken from Spiracle by Flower Face (bc it's The messed up time-looper Max song.) chapter title is from Pools by Glass Animals
CWs for this chapter: character death/suicide (impermanent), Max's category five nosebleeds, talk of Jefferson and what happened in the Dark Room, panic attacks, underage drinking, talk of drugs (but no actual doing them)"summary = "Max has been looping through this wretched week over and over in search of a less fatal outcome, but after yet another particularly bad ending, she's driven to do a little more than just reset. Consequences be damned."""

[[chapter]]
number = 1
text = """
Chloe’s jacket slips through her fingers. Max screams loud and long.

It’s drowned out by the screeching winds, the pounding rain, but even when her throat gives out her ears can pick up the sickening crack of Chloe’s body colliding with the rocks below. There’s a single moment of petrification, where all Max can see is Chloe’s limp, soaked form splayed across the cliff base. The way her right arm is twisted beyond repair. The smears of blood lining the rocks that her head had come into contact with on her descent. Then, the sea rises to swallow her whole, and Chloe is gone.

Chloe is _gone_.

Max glares down at the waves, and prays that Chloe washes up somewhere far, far away from here.

This isn't the first time she's watched Chloe die. Not by a long shot. With her constant rewinding and reliving this past week, Max has seen it 36 times, with incident marking the 37th. But it was different, this time.

It was all her fault.

It came purely, entirely, unquestionably from her own stubbornness. 36 dead Chloe Prices had proved too much for Max, and she'd been downright desperate to keep the girl alive this time around, to find a way to keep both her and the Bay safe and sound. But Chloe always was the more bullheaded of the two of them. She refused to have Max sacrifice the entire town just for her sake. So Max had watched, frozen, as Chloe wrenched herself from her grip and tumbled into the sea below.

Max's next thought is the overwhelming urge to tip herself over the edge and follow suit. To put an end to this agonizing cycle. Let the storm tear through Arcadia Bay and not do a fucking thing about it.

But habit takes over, fogs up her brain like thick, acrid smoke and before she can even blink Max has her hand raised to rewind. She watches the world spin and whirl and mix and blur, sea spray and whipping winds, fragmented stone and chunks of debris. There’s a sharp pang in the back of her head, and she can feel the blood dripping from her nose, but she doesn’t stop. Ripping pressure erupts at the base of her neck, like a thousand of those little needles all stuffed into the one spot, but she doesn’t stop. Her body aches and pounds and screams for her to stop, each individual nerve ripping apart at the seams, yet she does not lower her arm until it collapses under the weight of time compounded; leaving her panting, crying, bleeding on the ground.

With clipped breath and shaking arms, Max attempts to pull her phone from her jacket pocket. Her face nuzzles into the dirt beneath her, and she can see blood dampening the pebbles and patchy grass. Her limbs are papery, thin and weak and all too easy to shred, but she finally manages to bring the phone to her face. Getting her eyes to focus is another matter entirely, though the double vision fades in and out just enough for her to read a few numbers– always numbers, so many numbers, too many numbers in her head all the goddamn time.

10:17PM

A fit of coughs rattles through her ribcage. More. She needs more.

05/04/13

Her heart nearly stops.

Max makes her decision before she can even fully process what this all means. She forces herself to stand and tries her best to ignore the resulting roil of vertigo, as well as the steady dribble of blood from her nose and taste of iron lingering in her throat. Lurching forward, one weak leg in front of the other, each step sending sparks of pain rolling up her spine. She tries to pick up speed, she tries , but there’s a limp in her left leg and she only makes it a few blocks past Two Whales before she falls to the ground. She catches herself on one arm, but her face still scrapes against the sidewalk and she can feel the gravel scratching at her cheeks, soon followed by an unbearable stinging as dirt and dust are forced into her eyes.

She wants to scream again. To wail at the top of her lungs, to cry out for someone, anyone to help her. But no one can help her. She has to do this on her own. She always does. She drags herself back into a standing position, continuing her hobble up to Blackwell, hoping in vain to blink her vision back to normal and spitting a foul mix of blood and bile into the gutter.

Few people are wandering campus when she makes it, and they all stare incredulously as she shuffles past them. A few even call out to ask what she’s doing or if she needs a ride to the hospital. None of them recognize her, of course, but Max doesn’t care. All Max cares about is getting to Rachel before she can take a single goddamn step out of her dorm room.

She trips twice on the stairs, and she knows that she’s trailing blood all over the fresh tile flooring, but Max continues her climb regardless. She remembers the room number — Chloe had told her once, she doesn’t know when or where --- though she winds up not needing it. She can see the girl's name written in bold, red cursive on the whiteboard outside her door.

And she uses the last of her remaining energy to thunk herself against that door, too drained to even lift her hand to knock. Rachel’s voice floats through, and though it’s the first time Max has heard it she knows then that Chloe was right, that this girl is an angel.

“Hello?” she asks, and Max can hear her crossing the room in a huff. “Victoria, that better not be your drunk ass trying to get into the wrong room again.”

Rachel swings the door open with exceptional vigor and sends max tumbling to the floor in the process.

“Shit, fuck, what the hell---”

Max looks up at her through strained eyes, Rachel Amber and her ghostly afterimage dancing around each other in slow, sickly circles. The weight of the situation sinks in. Rachel is here. Rachel is alive. Max can save her, and save Chloe, and Kate, and put a stop to Jefferson and Nathan. She just has to keep track of every little moment, every little detail, every molecule of minutia going on around her. But she’s tired. She’s so, so tired. Already yesterday melds with tomorrow, fuses ten minutes from now to last Wednesday, mixes junkyard scrap with sunny snow.

“Can you hear me? C’mon, c’mon, talk to me.”

All the different incidents, outcomes and conversations swarm in Max’s mind and she’s hopeless; she’s desperate and dying on the Blackwell dorm floors and all she can get out are pleas so that’s what she does.

“J-Jefferson,” Max wheezes, coughs blood onto the floor beside her. “Dangerous. Don’t go. Please, please don’t go.”

A moment of tense silence follows. “The only place we’re going is the ER,” Rachel answers, distant and grim.

Panic seizes Max’s heart in a quick, crushing grip, and her body convulses in kind. “No hospital,” she begs, whimpering at the phantom smell of disinfectant, the muddled memory of a syringe pinching at her neck. She doesn’t know how many times it happened. “No hospital. No Jefferson.”

She can still feel his hands on her. The heat of the lights, the duct tape around her wrists. The cold floor against her face as Jefferson’s voice swung effortlessly between hazed praise and hellish anger. She can still see that photo of Rachel, huddled in the corner, bound but furious. The photos of Kate. The photos of herself.

“Okay, okay, no hospital. Just---Just try to breathe, alright?”

Max feels herself being pulled into a sitting position, leaned up against a body far studier than her own, warm cloth pressed against her face. She shudders through an inhale.

“That’s it, there you go.” Rachel’s voice treads the line between manic concern and stone cold calm, but Max can’t get enough of it. Every word out of her mouth translates straight into guilt-laden elation.

_I can save her_. Her mind rejoices, howls out in sweet, sombre victory. _I did it. I can save her. I can save them both_.

“Hey, hey.”

The ceiling rumbles with thunder. The walls flash white and bright.

“Stay with me, c’mon, stay with me.”

Max’s eyes roll back. Her mouth twitches up into a smile.

The world fades in and out for a little while, a tangled web of sights and sounds she left behind spinning and blooming into being. Despite how often it's happened at this point, Max will never get used to it. One minute she’s back in that storm, deafening winds and crackling lightning there to greet her with open arms. The next, she’s in The Dark Room, tied to that chair and staring down at the empty space where Victoria had been. Another blink, and she’s back in the dorms with Rachel’s signature red and black flannel held to her nose.

Rachel is on the phone with someone, all traces of her earlier composure having vanished. She still has an arm around Max, holding her steady as she speaks. “There’s blood- Like, _a lot_ of blood. And she won’t stop shaking.”

_Only because of the wind_, Max wants to say. But her throat is too tight, and Rachel’s voice is so hard to hear over the storm. Or maybe that’s just the blood rushing in her ears.

“She– She just showed up at my door and totally collapsed on me.”

Rachel looks pretty in the rain.

“She said no hospital. Fuck, man, I don’t know. Just get here as quick as you can.”

Max won't let anything happen to her. Not this time.

_Think, Max, think_, she tells herself, gazing up at the cut of Rachel's jawline, the calm blue of her feather earring. _You need to stop him. You need to save them._ She shifts a little, forces her heavy eyelids to stay open, willing her body to get back up and run to David's office. She hardly moves an inch.

"Take it easy. Are you back with me?"

Max shrugs as best she can. It doesn't matter to her if she's all there or not, all that matters is that she gets up.

"Need to… keep going." It takes a considerable amount of effort to form the words, like she's wading waist deep in a pool of cold molasses just to search for them. She struggles in vain to free herself from Rachel's grip.

"Uhm, no the fuck you don't," huffs Rachel, utterly flabbergasted and keeping Max still with barely any effort at all. "What you need to do is rest. And you certainly aren't gonna get any here in the palace of shitty mattresses and nosy neighbors, so I'm taking you to a friend's place."

She must mistake the desperation in Max's expression for fear, because she immediately continues, tone hushed and even.

"No hospital, just a friend. I promise. They've got a first aid kit, and the bed over there is _way_ comfier than mine. Trust me, you'll thank me later."

But she can't rest now, no matter how much she may want to. Not when she's so close. Not when she can save them both. Not when she knows there's an empty binder with Rachel's name on it. "Gotta… help…"

"_You_ need help." Max swears those hazel eyes are glowing, haloed, bright enough to scare away any shadow. "You look like you've been stuck out in the rain too, you poor thing."

Max could cry. She probably is, now that she thinks about it. She's never been so happy to be held in a dead girl's arms.

"Storm," the word tumbles from her lips with no resistance. "Always so c-c-cold."

Rachel makes this sort of horrified, sort of sad expression. Whatever she's feeling, her voice remains measured and steady. "I'll grab you something warm, and then we can see about getting you up. Sound good?"

Slowly, carefully, Rachel loosens her grip, allowing Max to sit on her own. Or try to, anyways, the waves of dizziness have yet to fully subside and Max has a pit in her stomach like her body thinks it might teeter into the ocean at any second, but it's nothing she hasn't dealt with before. She watches through her still swirling vision as Rachel rifles through her closet with all the speed and ferocity of a cracked out cheetah, pulling out the first sweater she can find and rushing back over to Max's side. It's a hoodie, and though the fabric's wear and tear is telling of its age it's no detriment to its comfort. The inside is lined with a soft fleece, and as Rachel zips it up Max can't help but let out a sigh of relief. It feels like it's been years since the last time she was warm.

Rachel keeps talking to her as they make their way down to the parking lot, gentle nothings and repetitive reassurances that are probably more for herself than for Max. She wards Victoria away with some sort of snappy remark, assures Kate that everything will be fine, gives Juliet a rushed explanation laced with white lies. Max isn't paying much attention to her little chameleon display, too preoccupied with plotting out her desired order of events.

First, she'll tell David, make sure he stops Jefferson before he can lay a hand on Rachel, Kate, or Victoria. Then, once she's found the courage to look the girl in the eyes after driving her to a suicide she can never remember, she'll apologize to Chloe, presumably introduce herself to Rachel in a less ominous context, and find some way to keep them both the hell away from Nathan. Simple. Easy.

"Yo, Rach. Over here."

Max freezes. She should have guessed. Who else would Rachel have been on the phone with.

"Chloe, thank fuck, let's–"

"Max?!"

Shit. Shit shit shit. It wasn't supposed to go this way, she didn't want Chloe to see her like this. Not again. She promised that she wouldn't. She needs more time, there’s never enough time.

But it's alright. She'll just rewind and–

Pain surges between her eyes, searing hot and jagged as the rocks beneath the lighthouse. She turned back all of three seconds. Too little to do anything meaningful, just enough to cause trouble.

"Chloe, thank fuck, let's– What the hell? When did she–"

Rachel is no longer at her side, now lagging a few steps behind. Max can hear her talking, but all she sees is Chloe.

Chloe, with her raggedy jacket and her striking blue hair. Chloe, with her gruff, familiar voice and oh so snarky attitude. Chloe, who Max loves more than anything. Chloe, who ripped herself from Max's arms and threw herself into the bay.

Chloe, alive, breathing, and looking right at her.

"Max?!"

Despite it all, relief hits her like a freight train. She gives a weak laugh at the comparison — though it’s more akin to a pitiful wheeze — and all of the adrenaline drains from her body in one fell swoop, leaving her battered and limp and so, so _happy_. She hits the asphalt with an echoing crunch.

“Oh God, oh God _Max_.”

“Shit, shit, she’s bleeding again, fuck.”

It’s almost funny, having Chloe and Rachel knelt at her side, staring down at her body for once. The world goes dark.

#align(center)[
    A groan tumbles from her numb lips. She tries to lift her heavy head.

    “Max! You fucked up my shot!”

    That voice, like ice prickling along her spine. She can’t get her body to move, to get up, to run .

    Not even when the storm rolls over the beachside, the lighthouse breaking away into big chunks of concrete all hurtling in her direction.

    Not even when she’s got her face mashed up against junkyard trash, watching the bullet rip through Chloe’s chest, Rachel dead and buried beneath them.

    She can hear him pushing the cart closer, the metallic grind and scrape of the wheels rolling across the floor, how the one in the top left corner squeaks at a slightly higher pitch than all the others.

    “Oh, Max.”

    He steps towards her in three slow strides. She knows what he's going to do. She knows , but can't do anything to stop it. She can never stop him. She'll always end up here, under his leering eyes, under his horrid touch.

    "You're almost more trouble than you're worth."

    A hand on her back. A pinch in her neck.

    "Almost."
]




"""
